[config.wallpaper]
set = false
command = ""

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify-colors.ini'
output_path = '~/.config/spicetify/Themes/Matugen/color.ini'
post_hook = 'spicetify apply'

[templates.vesktop]
input_path = '~/.config/matugen/templates/vesktop-quickcss.css'
output_path = '~/.config/vesktop/settings/quickCss.css'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -USR1 kitty'

[templates.cava]
input_path = '~/.config/matugen/templates/matugen-cava'
output_path = '~/.config/cava/config'
post_hook = 'pkill -USR1 cava'

[templates.zen]
input_path = '~/.config/matugen/templates/zen-userchrome.css'
output_path = '~/.config/zen-userchrome.css'
post_hook = 'notify-send "Zen Browser" "Reinicia Zen para aplicar los nuevos colores"'

[templates.vscode]
input_path = '~/.config/matugen/templates/vscode-colors.json'
output_path = '~/.config/matugen/vscode-colors-partial.json'
post_hook = 'bash ~/.config/matugen/merge-vscode-colors.sh'
