####################
### HYPRLAND.CONF ###
####################

# Colores generados por matugen (wallpaper → Material You)
source = ~/.config/hypr/colors.conf

###############
### MONITORS ###
###############

monitor = , preferred, auto, auto
monitor = eDP-1, prefered, auto, 1.33

###################
### MY PROGRAMS ###
###################

$terminal    = kitty
$fileManager = nautilus
$menu        = rofi -show drun

####################
### MODULES       ###
####################

source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/looknfeel.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/windowrules.conf

####################
### PLUGINS       ###
####################

plugin:hyprexpo {
    columns = 3
    gap_size = 5
    bg_col = rgb(111111)
    workspace_method = first 1
}
