####################
### AUTOSTART     ###
####################

exec-once = waybar & swaync & hypridle
exec-once = awww-daemon
exec-once = bash -c "sleep 2 && awww img ~/.config/hypr/current_wallpaper --transition-type any --transition-fps 60"
exec-once = bash -c "sleep 3 && spotify"
exec-once = bash -c "sleep 3 && kitty --class tty-clock-term -e ~/.config/hypr/scripts/tty-clock.sh"
exec-once = bash -c "sleep 3 && kitty --class cbonsai-term -e ~/.config/hypr/scripts/cbonsai.sh"
exec-once = bash -c "sleep 3 && kitty --class pipes-term -e ~/.config/hypr/scripts/pipes.sh"
exec-once = bash -c "sleep 1 && hyprctl dispatch workspace 2"
